title:            Oh My Stack
tagline:          JiangJun
description:      Sharing my notes and thoughts.
#Comment out url when working locally to resolve base urls correctly
url:              http://ohmystack.com

# Owner/author information
owner:
  name:           JiangJun
  avatar:         bio-photo.jpg
  bio:            "A fresh OpenStack developer."
  email:          jiangjun1990@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: ohmystack
  facebook:
  github: ohmystack
  linkedin: 
  instagram: ohmystack
  weibo: jiangjun1990
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus: https://plus.google.com/117576743349182606759/posts

# Analytics and webmaster tools stuff goes here
google_analytics: UA-45171468-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 4585663B2ABDEFFAEEBFA59399950B2C

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: Plans
    url: /plans

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter:    pygments
#markdown:    kramdown
markdown:    redcarpet

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  input: GFM    # using Github Flavored Markdown
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  # no_intra_emphasis: do not parse emphasis (underline) inside of words. Strings such as `foo_bar_baz`

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
encoding: UTF-8
paginate: 8
